# Generated by Django 5.2.5 on 2025-08-10 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=100)),
                ('preferred_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('admin', 'Admin'), ('forum', 'Forum'), ('student_portal', 'Student Portal'), ('public', 'Public')], max_length=50)),
                ('show_legal_name', models.BooleanField(default=False)),
                ('show_preferred_name', models.BooleanField(default=True)),
                ('show_username', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.identityprofile')),
            ],
        ),
    ]
