# Generated by Django 5.2.5 on 2025-08-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityprofile',
            name='legal_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='preferred_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visibilityrule',
            name='context',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Forum', 'Forum'), ('Student Portal', 'Student Portal'), ('Public', 'Public')], max_length=50),
        ),
        migrations.AlterField(
            model_name='visibilityrule',
            name='show_preferred_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visibilityrule',
            name='show_username',
            field=models.BooleanField(default=False),
        ),
    ]
