# Generated by Django 5.2.5 on 2025-08-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_identityprofile_legal_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identityprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='identityprofile',
            name='display_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='visibilityrule',
            unique_together={('profile', 'context')},
        ),
    ]
